# Generated by Django 3.1.3 on 2020-12-11 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20201211_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomeproduct',
            name='store_name',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.store'),
        ),
    ]
