# Generated by Django 3.1.3 on 2020-12-11 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_store_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='store',
            field=models.ForeignKey(default=None,null=True ,on_delete=django.db.models.deletion.DO_NOTHING, to='products.store'),
        ),
    ]
