# Generated by Django 3.1.3 on 2020-12-12 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20201211_2114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='store',
            new_name='store_name',
        ),
    ]
