# Generated by Django 3.1.3 on 2020-12-13 11:57

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20201213_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='store_name', chained_model_field='store_name', on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
